exclude: "^docs/|/migrations/|/templates/"
default_stages: [pre-commit]

# General hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: name-tests-test
        args: [ "--django" ]

# Ruff hook
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
    -   id: ruff
        alias: autoformat
        args: [--fix]
